title: "Slektstre med NetworkX"
author: "Arvid Lundervold"

execute:
  execute_notebooks: "off"

sphinx:
  config:
    extensions:
      - myst_nb
      - sphinx_book_theme
      - sphinx_copybutton
    # Disable problematic extensions
    exclude_patterns:
      - "**/.*"
    # Suppress warnings
    suppress_warnings:
      - myst.header
      - myst.note