name: slektstre
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - networkx>=3.0
  - matplotlib>=3.7
  - jupyter>=1.0
  - pydantic>=2.0
  - pyyaml>=6.0
  - pandas>=2.0
  - plotly>=5.0
  - ipywidgets>=8.0
  - pillow>=10.0
  # Book generation dependencies
  - jupyter-book>=0.15.0
  - sphinx>=5.0.0
  - sphinx-book-theme>=1.0.0
  - myst-nb>=0.17.0
  - nbconvert>=7.0.0
  - pandoc>=3.0.0
  - pip
  - pip:
    - python-dateutil>=2.8
    - kaleido>=0.2.1
    # Additional book generation packages
    - PyPDF2>=3.0.0
    - playwright>=1.55.0
    - beautifulsoup4>=4.12.0
    - watchdog>=3.0.0
