name: slektstre
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - networkx>=3.0
  - matplotlib>=3.7
  - jupyter>=1.0
  - pydantic>=2.0
  - pyyaml>=6.0
  - pandas>=2.0
  - plotly>=5.0
  - ipywidgets>=8.0
  - pillow>=10.0
  - pip
  - pip:
    - python-dateutil>=2.8
