name: Deploy Jupyter Book to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install jupyter nbconvert

    - name: Install system dependencies for PDF generation
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-xetex texlive-fonts-recommended texlive-latex-extra

    - name: Build HTML book
      run: |
        make book-html
        # Create index.html manually since nbconvert doesn't create it
        python -c "
import os
os.makedirs('_build/html', exist_ok=True)
with open('_build/html/index.html', 'w', encoding='utf-8') as f:
    f.write('''<!DOCTYPE html>
<html lang=\"no\">
<head>
    <meta charset=\"UTF-8\">
    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">
    <title>Slektstre med NetworkX - Family Trees with NetworkX</title>
    <style>
        body { font-family: -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, sans-serif; line-height: 1.6; max-width: 1200px; margin: 0 auto; padding: 20px; background-color: #f8f9fa; }
        .container { background: white; padding: 40px; border-radius: 10px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
        h1 { color: #2c3e50; text-align: center; border-bottom: 3px solid #3498db; padding-bottom: 20px; margin-bottom: 30px; }
        .subtitle { text-align: center; color: #7f8c8d; font-size: 1.2em; margin-bottom: 40px; }
        .version-info { background: #ecf0f1; padding: 15px; border-radius: 5px; text-align: center; margin-bottom: 30px; font-weight: bold; }
        .notebook-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(300px, 1fr)); gap: 20px; margin-bottom: 40px; }
        .notebook-card { background: #fff; border: 1px solid #ddd; border-radius: 8px; padding: 20px; transition: transform 0.2s, box-shadow 0.2s; }
        .notebook-card:hover { transform: translateY(-2px); box-shadow: 0 4px 15px rgba(0,0,0,0.1); }
        .notebook-card h3 { color: #2c3e50; margin-top: 0; }
        .notebook-card p { color: #7f8c8d; margin-bottom: 15px; }
        .notebook-card a { display: inline-block; background: #3498db; color: white; padding: 10px 20px; text-decoration: none; border-radius: 5px; transition: background 0.2s; }
        .notebook-card a:hover { background: #2980b9; }
        .footer { text-align: center; margin-top: 40px; padding-top: 20px; border-top: 1px solid #ddd; color: #7f8c8d; }
        .badges { text-align: center; margin-bottom: 30px; }
        .badges a { display: inline-block; margin: 0 10px; text-decoration: none; }
    </style>
</head>
<body>
    <div class=\"container\">
        <h1>🌳 Slektstre med NetworkX</h1>
        <div class=\"subtitle\">Family Trees with NetworkX</div>
        <div class=\"version-info\">Versjon 1.01 - 12 Oktober 2025<br>Version 1.01 - October 12, 2025</div>
        <div class=\"badges\">
            <a href=\"https://github.com/arvidl/slektstre\"><img src=\"https://img.shields.io/badge/GitHub-Repository-blue?logo=github\" alt=\"GitHub Repository\"></a>
            <a href=\"https://opensource.org/licenses/MIT\"><img src=\"https://img.shields.io/badge/License-MIT-yellow.svg\" alt=\"License: MIT\"></a>
            <a href=\"https://www.python.org/downloads/\"><img src=\"https://img.shields.io/badge/python-3.8+-blue.svg\" alt=\"Python 3.8+\"></a>
        </div>
        <p style=\"text-align: center; font-size: 1.1em; color: #2c3e50;\">
            Et Python-bibliotek for å bygge, administrere og visualisere familie-trær ved hjelp av NetworkX og Jupyter notebooks.<br>
            <em>A Python library for building, managing and visualizing family trees using NetworkX and Jupyter notebooks.</em>
        </p>
        <div class=\"notebook-grid\">
            <div class=\"notebook-card\"><h3>📚 00 - Slektstrær og Grafer</h3><p>Introduksjon til slektstrær og grafteori.</p><a href=\"00_slektstraer_og_grafer.html\">Åpne Notebook</a></div>
            <div class=\"notebook-card\"><h3>📖 01 - Introduksjon</h3><p>Oversikt over slektstre-prosjektet.</p><a href=\"01_introduksjon.html\">Åpne Notebook</a></div>
            <div class=\"notebook-card\"><h3>🔨 02 - Bygge Slektstre Manuelt</h3><p>Lær å bygge slektstrær programmatisk.</p><a href=\"02_bygg_tre_manuelt.html\">Åpne Notebook</a></div>
            <div class=\"notebook-card\"><h3>📥 03 - Importere og Eksportere Data</h3><p>Hvordan importere og eksportere familie-data.</p><a href=\"03_importer_data.html\">Åpne Notebook</a></div>
            <div class=\"notebook-card\"><h3>📊 04 - Visualisering</h3><p>Alle visualiseringsalternativer.</p><a href=\"04_visualisering.html\">Åpne Notebook</a></div>
            <div class=\"notebook-card\"><h3>🌐 05 - Eksterne Databaser</h3><p>Integrasjon med genealogi-databaser.</p><a href=\"05_eksterne_databaser.html\">Åpne Notebook</a></div>
        </div>
        <div class=\"footer\">
            <p><strong>Forfatter:</strong> Arvid Lundervold<br><strong>GitHub:</strong> <a href=\"https://github.com/arvidl/slektstre\">https://github.com/arvidl/slektstre</a></p>
        </div>
    </div>
</body>
</html>''')
"

    - name: Setup Pages
      uses: actions/configure-pages@v3

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: _build/html

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2

    - name: Build PDF book
      run: |
        make book-pdf

    - name: Upload PDF as artifact
      uses: actions/upload-artifact@v3
      with:
        name: book-pdf
        path: _build/latex/book.pdf
        retention-days: 30
